#String Operation
#capitalize()
s="ANAS momin"
print("Original =",s,end='\n\n')
print("capitalize =",s.capitalize())
#title()
print("title =",s.title())
#casefold()
#lower()
print("case fold =",s.casefold())
print("lower =",s.lower())
#upper()
print("upper =",s.upper())
#swapcase()
print("swapcase =",s.swapcase())
#isupper()
print("isupper =",s.isupper())
#islower
print("islower =",s.islower())
#find()
print("find =",s.find('A'))
