#Q3.Write a program to use a variable with dynamic initialization check and display its type and value by entering different values.
a=int(input(" Enter int value="))
b=float(input(" Enter float value="))
c=input(" Enter char value=")
d=input(" Enter string value=")
e=bool(input(" Enter boolean value="))
print(a)
print("type of a=",type(a))
print(b)
print("type of b=",type(b))
print(c)
print("type of c=",type(c))
print(d)
print("type of d=",type(d))
print(e)
print("type of a=",type(e))
