a=int(input("Enter one Int value="))
b=float(input("Enter one Float value="))
print("Addtion=",a+b)
print("Subraction=",a-b)
print("Division=",a/b)
print("Multiplication=",a*b)
print("Floor Div=",a//b)
print("Exponent=",a**b)
