a=int(input("Enter a Int value="))
b=float(input("Enter a Float value="))
c=input("Enter a Char value=")
d=input("Enter a String value=")
e=bool(input("Enter a boolean value="))
print("value Int value=",a)
print("value Float value=",b)
print("value char value=",c)
print("value String value=",d)   
print("value Boolean value=",e)
